# =============================================================================
# Docker Compose para Desenvolvimento
# =============================================================================
# Uso: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  # API em modo desenvolvimento com hot reload
  solis-api:
    build:
      target: development
    volumes:
      - ./solis-api:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  # Agente PDV em modo desenvolvimento
  agente-pdv:
    volumes:
      - ./agente-pdv:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # Solis PWA em modo desenvolvimento
  solis-pwa:
    command: npm run start
    ports:
      - "3001:3000"
    volumes:
      - ./solis-pwa:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  # Solis Admin em modo desenvolvimento
  solis-admin:
    command: npm run start
    ports:
      - "3002:3000"
    volumes:
      - ./solis-admin:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  # Adminer para gerenciar o banco de dados
  adminer:
    image: adminer:latest
    container_name: solis-adminer
    ports:
      - "8082:8080"
    networks:
      - solis-network
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=nette